using System.ComponentModel.DataAnnotations;
using Blazorise;

namespace PubNet.Frontend.Services;

/// <summary>
/// Validators for Blazorise <c>Validation</c> components.
/// </summary>
/// <remarks>
/// The request DTOs are generated by Kiota and therefore carry no data annotations, so
/// <c>Validations.ValidateAll()</c> has nothing to validate against unless a validator is supplied
/// explicitly. A <c>Validation</c> element without one silently accepts any input.
/// </remarks>
public static class FormValidators
{
	private static readonly EmailAddressAttribute EmailAddress = new();

	/// <summary>
	/// Rejects null, empty and whitespace-only values.
	/// </summary>
	public static void Required(ValidatorEventArgs e, string fieldName)
	{
		var value = Convert.ToString(e.Value);

		if (string.IsNullOrWhiteSpace(value))
			Fail(e, $"{fieldName} is required");
		else
			Pass(e);
	}

	/// <summary>
	/// Rejects null, empty and whitespace-only values, as well as anything that is not an e-mail address.
	/// </summary>
	public static void RequiredEmail(ValidatorEventArgs e)
	{
		var value = Convert.ToString(e.Value);

		if (string.IsNullOrWhiteSpace(value))
			Fail(e, "E-Mail is required");
		else if (!EmailAddress.IsValid(value))
			Fail(e, "Please enter a valid e-mail address");
		else
			Pass(e);
	}

	/// <summary>
	/// Accepts empty values, but requires anything else to be an absolute HTTP(S) URL so it can be linked to.
	/// </summary>
	public static void OptionalUrl(ValidatorEventArgs e)
	{
		var value = Convert.ToString(e.Value);

		if (string.IsNullOrWhiteSpace(value))
		{
			Pass(e);

			return;
		}

		if (Uri.TryCreate(value, UriKind.Absolute, out var uri) &&
			(uri.Scheme == Uri.UriSchemeHttp || uri.Scheme == Uri.UriSchemeHttps))
			Pass(e);
		else
			Fail(e, "Please enter a full URL, including https://");
	}

	private static void Pass(ValidatorEventArgs e)
	{
		e.Status = ValidationStatus.Success;
		e.ErrorText = null;
	}

	private static void Fail(ValidatorEventArgs e, string message)
	{
		e.Status = ValidationStatus.Error;
		e.ErrorText = message;
	}
}
