// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PubNet.Client.Generated.Packages.Nuget.Registrations.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PubNet.Client.Generated.Packages.Nuget.Registrations
{
    /// <summary>
    /// Builds and executes requests for operations under \Packages\Nuget\Registrations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class RegistrationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the PubNet.Client.Generated.Packages.Nuget.Registrations.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::PubNet.Client.Generated.Packages.Nuget.Registrations.Item.RegistrationsItemRequestBuilder"/></returns>
        public global::PubNet.Client.Generated.Packages.Nuget.Registrations.Item.RegistrationsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::PubNet.Client.Generated.Packages.Nuget.Registrations.Item.RegistrationsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PubNet.Client.Generated.Packages.Nuget.Registrations.RegistrationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegistrationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Packages/Nuget/Registrations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PubNet.Client.Generated.Packages.Nuget.Registrations.RegistrationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegistrationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Packages/Nuget/Registrations", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
