// <auto-generated/>
using ApiSdk.Packages.Nuget.Package.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Packages.Nuget.Package {
    /// <summary>
    /// Builds and executes requests for operations under \Packages\Nuget\Package
    /// </summary>
    public class PackageRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the ApiSdk.Packages.Nuget.Package.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public PackageItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("id", position);
            return new PackageItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new PackageRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PackageRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Packages/Nuget/Package", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new PackageRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PackageRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Packages/Nuget/Package", rawUrl) {
        }
    }
}
