// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PubNet.Client.Generated.Packages.Dart;
using PubNet.Client.Generated.Packages.Nuget;
using PubNet.Client.Generated.Packages.Search;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PubNet.Client.Generated.Packages
{
    /// <summary>
    /// Builds and executes requests for operations under \Packages
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class PackagesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Dart property</summary>
        public global::PubNet.Client.Generated.Packages.Dart.DartRequestBuilder Dart
        {
            get => new global::PubNet.Client.Generated.Packages.Dart.DartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Nuget property</summary>
        public global::PubNet.Client.Generated.Packages.Nuget.NugetRequestBuilder Nuget
        {
            get => new global::PubNet.Client.Generated.Packages.Nuget.NugetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Search property</summary>
        public global::PubNet.Client.Generated.Packages.Search.SearchRequestBuilder Search
        {
            get => new global::PubNet.Client.Generated.Packages.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PubNet.Client.Generated.Packages.PackagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PackagesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Packages", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PubNet.Client.Generated.Packages.PackagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PackagesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Packages", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
