// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace PubNet.Client.Generated.Models {
    public class NugetPackageDependencyGroupDto : IParsable {
        /// <summary>The dependencies property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<NugetPackageDependencyDto>? Dependencies { get; set; }
#nullable restore
#else
        public List<NugetPackageDependencyDto> Dependencies { get; set; }
#endif
        /// <summary>The targetFramework property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetFramework { get; set; }
#nullable restore
#else
        public string TargetFramework { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static NugetPackageDependencyGroupDto CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new NugetPackageDependencyGroupDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"dependencies", n => { Dependencies = n.GetCollectionOfObjectValues<NugetPackageDependencyDto>(NugetPackageDependencyDto.CreateFromDiscriminatorValue)?.ToList(); } },
                {"targetFramework", n => { TargetFramework = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<NugetPackageDependencyDto>("dependencies", Dependencies);
            writer.WriteStringValue("targetFramework", TargetFramework);
        }
    }
}
