// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace PubNet.Client.Generated.Models {
    public class PackageListCollection : IParsable 
    {
        /// <summary>The dart property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public DartPackageListDto? Dart { get; set; }
#nullable restore
#else
        public DartPackageListDto Dart { get; set; }
#endif
        /// <summary>The nuget property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public NugetPackageListDto? Nuget { get; set; }
#nullable restore
#else
        public NugetPackageListDto Nuget { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="PackageListCollection"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static PackageListCollection CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new PackageListCollection();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"dart", n => { Dart = n.GetObjectValue<DartPackageListDto>(DartPackageListDto.CreateFromDiscriminatorValue); } },
                {"nuget", n => { Nuget = n.GetObjectValue<NugetPackageListDto>(NugetPackageListDto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<DartPackageListDto>("dart", Dart);
            writer.WriteObjectValue<NugetPackageListDto>("nuget", Nuget);
        }
    }
}
