// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PubNet.Client.Generated.Packages.Dart.Item.Item.AnalysisJson;
using PubNet.Client.Generated.Packages.Dart.Item.Item.ArchiveTarGz;
using PubNet.Client.Generated.Packages.Dart.Item.Item.Docs;
using PubNet.Client.Generated.Packages.Dart.Item.Item.Retract;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PubNet.Client.Generated.Packages.Dart.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \Packages\Dart\{name}\{version}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class WithVersionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The analysisJson property</summary>
        public global::PubNet.Client.Generated.Packages.Dart.Item.Item.AnalysisJson.AnalysisJsonRequestBuilder AnalysisJson
        {
            get => new global::PubNet.Client.Generated.Packages.Dart.Item.Item.AnalysisJson.AnalysisJsonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The archiveTarGz property</summary>
        public global::PubNet.Client.Generated.Packages.Dart.Item.Item.ArchiveTarGz.ArchiveTarGzRequestBuilder ArchiveTarGz
        {
            get => new global::PubNet.Client.Generated.Packages.Dart.Item.Item.ArchiveTarGz.ArchiveTarGzRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Docs property</summary>
        public global::PubNet.Client.Generated.Packages.Dart.Item.Item.Docs.DocsRequestBuilder Docs
        {
            get => new global::PubNet.Client.Generated.Packages.Dart.Item.Item.Docs.DocsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Retract property</summary>
        public global::PubNet.Client.Generated.Packages.Dart.Item.Item.Retract.RetractRequestBuilder Retract
        {
            get => new global::PubNet.Client.Generated.Packages.Dart.Item.Item.Retract.RetractRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PubNet.Client.Generated.Packages.Dart.Item.Item.WithVersionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVersionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Packages/Dart/{name}/{version}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PubNet.Client.Generated.Packages.Dart.Item.Item.WithVersionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVersionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Packages/Dart/{name}/{version}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
