// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using PubNet.Client.Generated.Packages.Nuget.Registrations.Item.IndexJson;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace PubNet.Client.Generated.Packages.Nuget.Registrations.Item {
    /// <summary>
    /// Builds and executes requests for operations under \Packages\Nuget\Registrations\{id}
    /// </summary>
    public class RegistrationsItemRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The indexJson property</summary>
        public IndexJsonRequestBuilder IndexJson
        {
            get => new IndexJsonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="RegistrationsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegistrationsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Packages/Nuget/Registrations/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="RegistrationsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegistrationsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Packages/Nuget/Registrations/{id}", rawUrl)
        {
        }
    }
}
