// <auto-generated/>
using ApiSdk.Packages.Nuget.Item.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Packages.Nuget.Item {
    /// <summary>
    /// Builds and executes requests for operations under \Packages\Nuget\{id}
    /// </summary>
    public class NugetItemRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the ApiSdk.Packages.Nuget.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithVersionItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("version", position);
            return new WithVersionItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new NugetItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NugetItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Packages/Nuget/{id}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new NugetItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NugetItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Packages/Nuget/{id}", rawUrl) {
        }
    }
}
