name: Release Please

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
