generate:
	kiota generate --openapi PubNet.API/openapi-spec.json --language CSharp --output PubNet.Client.Generated --namespace-name PubNet.Client.Generated --exclude-backward-compatible

update:
	kiota update --output PubNet.Client.Generated
